# Generated by Django 5.0.3 on 2024-04-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='buyer_dni',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chair',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
